config/routes.rb
Streetmom::Application.routes.draw do

  devise_for :users, path_prefix: 'my'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  resources :reports, except: %w(edit) do
    collection do
      get 'active'
      get 'history'
    end

    member do
      post 'upload' => 'reports#update'
      get 'download' => 'reports#download', :as => :download
    end
  end

  resources :users, except: %w(destroy) do
    collection do
      get 'by_phone'
      get 'deactivated'
    end
    member do
      post 'start', to: 'shifts#start', :as => :start_shift
      post  'end',  to: 'shifts#end',   :as => :end_shift
    end
  end

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

  resources :clients, except: %w(destroy) do
    collection do
      get 'deactivated'
    end
  end

  resources :dispatches, only: %w(create update)
  resources :logs,       only: %w(create update)
  resources :reporters,  only: %w(show create new)
  resources :sms,        only: %w(create)

  resources :reporter_locations, only: %w(create)

  resources :uploads,    only: %w(destroy)

  resources :timeline_map do
    collection do
      get 'timeline_map' => 'timeline_map#index'
    end
  end

  get '/visualizations/reports_timeline_map', to: 'visualizations#reports_timeline_map'

  get '/visualizations/reports_charts', to: 'visualizations#reports_charts'
end

app/models/user.rb
class User < ActiveRecord::Base
  include CsvExportable
  sensitive_fields :phone, :name

  devise :database_authenticatable, :recoverable, :registerable,
         :rememberable, :trackable, :validatable

  # RELATIONS #
  has_one    :responder,  class_name: 'Responder', foreign_key: :id
  has_one    :dispatcher, class_name: 'Dispatcher', foreign_key: :id
  has_one    :reporter, class_name: 'Reporter', foreign_key: :id
  has_many   :shifts,     dependent: :destroy
  has_many   :reporter_locations, dependent: :destroy

  # CALLBACKS #
  after_validation :make_unavailable, on: :update

  # CONSTANTS #
  ROLES = %w(responder dispatcher reporter)

  # VALIDATIONS #
  validates :phone,  length: { is: 10 }, uniqueness: true
  validates :name,   presence: true, uniqueness: true
  validates_inclusion_of :role, in: ROLES

  # SCOPES #
  scope :active,      -> { where(active: true) }
  scope :inactive,    -> { where(active: false) }
  scope :dispatchers, -> { where(role: 'dispatcher') }
  scope :responders,  -> { where(role: 'responder') }
  scope :reporters,  -> { where(role: 'reporter') }
  scope :on_shift,    -> { where(id: Shift.on.map(&:user_id)) }

  # INSTANCE METHODS #
  def become_child
    dispatcher || responder
  end

  def dispatcher?
    role == 'dispatcher'
  end

  def responder?
    role == 'responder'
  end

  def reporter?
    role == 'reporter'
  end

  def phone=(new_phone)
    write_attribute(:phone, NumberSanitizer.sanitize(new_phone))
  rescue NoMethodError
    errors.add(:phone, 'Phone Number is not valid')
  end

  def make_unavailable
    shifts.end('web') if active_changed? && !active
  end

  def active_for_authentication?
    super && active
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
	 before_filter :find_user

	def is_user_responder
    status = @user.present? && @user.responder?
    render json: { result_value: status }
  end

  def has_responder_shift_started
    status = @user.on_duty
    render json: { result_value: status }
  end

  def start_responder_shift
  	@user.update(on_duty: true)
  	head :ok
  end

  def end_responder_shift
  	@user.update(on_duty: false)
  	head :ok
  end

private

  def find_user
    @user = User.find_by_phone(NumberSanitizer.sanitize(params[:phone]))
  end

end

app/controllers/users_controller.rb
class UsersController < DashboardController
  before_filter :find_user, only: [:show, :update, :edit]
  before_filter :authenticate_admin!,      only:   :create
  before_filter :authenticate_user!,       except: :create
  before_filter :authenticate_dispatcher!, except: :create

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "#{@user.name}'s profile was created"
      user_signed_in? ? (redirect_to action: :index) : (redirect_to :back)
    else
      flash[:notice] = @user.errors.full_messages.join(', ')
      user_signed_in? ? (render :new) : (redirect_to :back)
    end
  end

  def by_phone
    @user = User.find_by_phone(NumberSanitizer.sanitize(params[:phone]))
    if @user.present?
      render json: @user
    else
      head :not_found
    end
  end

  def deactivated
    @responders = Responder.inactive
    @dispatchers = Dispatcher.inactive
  end

  def edit
  end

  def index
    @responders = Responder.active
    @dispatchers = Dispatcher.active
  end

  def new
    @user = User.new
  end

  def show
    @user = @user.become_child
  end

  def update
    respond_to do |format|
      if @user.update_attributes(user_params)

        format.json {render json: @user}
        format.html {
          flash[:notice] = "#{@user.name} successfully updated"
          redirect_to @user
        }
      else
        format.json {render json: @user}
        format.html {
          flash[:notice] = "Error updating #{@user.name}"
          render action: :edit
        }
      end
    end
  end

  private

  def authenticate_admin!
    user_signed_in? && (current_user.dispatcher? || authenticate_super_admin!)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:active, :phone, :name, :role, :email, :password, :password_confirmation)
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/views/users/_dispatch_table.html.haml
- if dispatches.present?
  %table.table.table-condensed
    %thead
      %tr
        %th Date
        %th Address
        %th Status
        %th
    %tbody
      - dispatches.each do |dispatch|
        %tr
          - report = dispatch.report
          = content_tag_for :tr, report, class: row_style(dispatch.status) do
            %td= dispatch.created_at.in_time_zone(Streetmom::TIME_ZONE).strftime('%-m-%-d-%y')
            %td= report.address
            %td= dispatch.status.capitalize
            %td= link_to 'Details', report_path(report)
- else
  %weak Responder has not been dispatched to a report yet.

app/views/users/_form.html.haml
= f.input :name
= f.input :phone, as: :tel
= f.input :email, as: :email
= f.input :role, collection: User::ROLES
- if f.object.new_record?
  = f.input :password
  = f.input :password_confirmation
= f.button :submit

app/views/users/_password_form.html.haml
= simple_form_for user, as: :user, url: user_registration_path do |f|
  = f.input :password, autocomplete: 'off'
  = f.input :password_confirmation, autocomplete: 'off'
  = f.input :current_password, autocompleted: 'off'
  = f.button :submit, 'Change Password'
%hr
= link_to 'Back', :back, class: 'btn btn-default'

app/views/users/_shift_table.html.haml
- if shifts.present?
  %h3 Shifts
  %table.table.table-condensed
    %thead
      %th Date
      %th
        Time
        = "(24 hour, #{Time.now.in_time_zone(time_zone)})"
    %tbody
      - shifts.each do |shift|
        %tr
          - shift_presenter = ShiftPresenter.new(shift)
          %td= shift_presenter.date
          %td= shift_presenter.time

app/views/users/_table.html.haml
%table.table.pusher
  %thead
    %tr
      %th Name
      %th Phone
      %th Email
      - if users[0].responder?
        %th Completed
        %th Rejected
      - if !deactivated
        %th Available
      - if !deactivated && users[0].responder?
        %th Current Status
  %tbody
    - users.each do |user|
      = content_tag_for :tr, user do
        %th= link_to user.name, user_path(user)
        %td.phone= user.phone
        %td= link_to user.email, "mailto:#{user.email}"
        - if user.responder?
          %td= user.dispatches.completed_count
          %td= user.dispatches.rejected_count
        - if !deactivated
          %td
            - path = user.shifts.started? ? end_shift_user_path(user) : start_shift_user_path(user)
            = simple_form_for '', url: path, method: :post do |f|
              = f.check_box :available, checked: user.shifts.started?, class: 'availability'
        - if !deactivated && user.responder?
          %td= ResponderPresenter.new(user).status

app/views/users/_users_table.html.haml
- if responders.present?
  %h3 Responders
  = render 'table', users: responders, deactivated: deactivated
- else
  %p.notice
    %br There are no responders to show.
- if dispatchers.present?
  %h3 Dispatchers
  = render 'table', users: dispatchers, deactivated: deactivated
- else
  %p.notice
    %br There are no dispatchers to show.

app/views/users/deactivated.html.haml
.row
  %h2.col-sm-6 Deactivated Users
  .table-top-button.col-sm-1.col-sm-offset-4= link_to 'Active Users', users_path, class: 'btn btn-primary'
= render 'users_table', deactivated: true, dispatchers: @dispatchers, responders: @responders

app/views/users/edit.html.haml
%h2= "Edit #{@user.name}"
- if @user.responder?
  - user = @user.become_child
  - path = user.shifts.started? ? end_shift_user_path(user) : start_shift_user_path(user)
  = simple_form_for '', url: path, method: :post do |f|
    .availability
      = f.check_box :available, class: "available", :label => false, :inline_label => true, checked: user.shifts.started?
      %strong Available

= simple_form_for @user do |f|
  = render 'form', f: f
%hr
= render 'password_form', user: current_user if !@user.new_record? && @user == current_user

app/views/users/index.html.haml
.row
  %h2.col-sm-2 Users
  .table-top-button.col-sm-1.col-sm-offset-8= link_to 'New User', new_user_path, class: 'btn btn-primary'
= render 'users_table', deactivated: false, dispatchers: @dispatchers, responders: @responders
.row
  %br
  .col-sm-2= link_to 'Inactive Users', deactivated_users_path, class: 'btn btn-warning'

app/views/users/new.html.haml
%h2 Create User
= simple_form_for @user do |f|
  = render 'form', f: f

app/views/users/show.html.haml
.row
  .col-md-5
    %h1.name= "#{@user.name} (#{@user.role.capitalize})"
  .col-md-5.col-md-offset-2
    %br
    - if @user.active
      - path = @user.shifts.started? ? end_shift_user_path(@user) : start_shift_user_path(@user)
      = simple_form_for '', url: path, method: :post do |f|
        .availability
          = f.check_box :available, class: "available", :label => false, :inline_label => true, checked: @user.shifts.started?
          %strong Available
    - elsif !@user.active
      %strong Inactive

    .phone= @user.phone
    .email= link_to @user.email, "mailto:#{@user.email}"

- if @user.responder?
  %br
  = render 'shift_table', shifts: @user.shifts, time_zone: Streetmom::TIME_ZONE
  %br
  = render 'dispatch_table', dispatches: @user.dispatches

.row
  %br
  - status = @user.active ? 'Deactivate' : 'Reactivate'
  .col-sm-2= link_to "#{status} #{@user.role.capitalize}", user_path(@user, user: {active: !@user.active}), method: :put, class: 'btn btn-warning'
  .col-sm-2= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default'