config/routes.rb
Streetmom::Application.routes.draw do

  devise_for :users, path_prefix: 'my'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  resources :reports, except: %w(edit) do
    collection do
      get 'active'
      get 'history'
    end

    member do
      post 'upload' => 'reports#update'
      get 'download' => 'reports#download', :as => :download
    end
  end

  resources :users, except: %w(destroy) do
    collection do
      get 'by_phone'
      get 'deactivated'
    end
    member do
      post 'start', to: 'shifts#start', :as => :start_shift
      post  'end',  to: 'shifts#end',   :as => :end_shift
    end
  end

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

  resources :clients, except: %w(destroy) do
    collection do
      get 'deactivated'
    end
  end

  resources :dispatches, only: %w(create update)
  resources :logs,       only: %w(create update)
  resources :reporters,  only: %w(show create new)
  resources :sms,        only: %w(create)

  resources :reporter_locations, only: %w(create)

  resources :uploads,    only: %w(destroy)

  resources :timeline_map do
    collection do
      get 'timeline_map' => 'timeline_map#index'
    end
  end

  get '/visualizations/reports_timeline_map', to: 'visualizations#reports_timeline_map'

  get '/visualizations/reports_charts', to: 'visualizations#reports_charts'
end

app/models/client.rb
class Client < ActiveRecord::Base
  include CsvExportable
  sensitive_fields :name

  # RELATIONS #
  has_many :reports

  AGEGROUP    = [
    'Youth (0-17)', 'Young Adult (18-34)', 'Adult (35-64)', 'Senior (65+)'
  ]
  GENDER      = %w(Male Female Other)
  ETHNICITY   = [
    'Hispanic or Latino', 'American Indian or Alaska Native', 'Asian',
    'Black or African American', 'Native Hawaiian or Pacific Islander',
    'White', 'Other/Unknown'
  ]

  validates_inclusion_of :gender, in: GENDER, allow_blank: true
  validates_inclusion_of :age, in: AGEGROUP, allow_blank: true
  validates_inclusion_of :race, in: ETHNICITY, allow_blank: true

  # CALLBACKS #

  # SCOPES #
  scope :active,      -> { where(active: true) }
  scope :inactive,    -> { where(active: false) }

  # CLASS METHODS #

  # INSTANCE METHODS #
  private
end

app/controllers/clients_controller.rb
class ClientsController < DashboardController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = Client.active
  end

  def deactivated
    @clients = Client.inactive
  end

  def show
    @available_responders = Responder.available
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :age, :gender, :race, :active)
    end
end

app/views/clients/_clients_table.html.haml
%table.table.pusher
  %thead
    %tr
      %th Name
      %th Age
      %th Gender
      %th Ethnicity
      %th Reports
  %tbody
    - clients.each do |client|
      = content_tag_for :tr, client do
        %th= link_to client.name, client_path(client)
        %td= client.age
        %td= client.gender
        %td= client.race
        %td= client.reports.count

app/views/clients/_form.html.haml
= f.input :name
= f.input :gender, collection: Client::GENDER
= f.input :age, collection: Client::AGEGROUP
= f.input :race, collection: Client::ETHNICITY
= f.button :submit

app/views/clients/deactivated.html.haml
.row
  %h2.col-sm-6 Deactivated Clients
  .table-top-button.col-sm-1.col-sm-offset-4= link_to 'Active Clients', clients_path, class: 'btn btn-primary'
= render 'clients_table', clients: @clients

app/views/clients/edit.html.haml
%h2= "Edit #{@client.name}"
= simple_form_for @client do |f|
  = render 'form', f: f

app/views/clients/index.html.haml
.row
  %h2.col-sm-2 Clients
  .table-top-button.col-sm-1.col-sm-offset-8= link_to 'New Client', new_client_path, class: 'btn btn-primary'
= render 'clients_table', clients: @clients
.row
  %br
  .col-sm-2= link_to 'Inactive Clients', deactivated_clients_path, class: 'btn btn-warning'

app/views/clients/new.html.haml
%h2 Create Client
= simple_form_for @client do |f|
  = render 'form', f: f

app/views/clients/show.html.haml
.row
  .col-md-5
    %h1.name= "#{@client.name}"
  .col-md-5.col-md-offset-2
    %br
    - if !@client.active
      %strong Inactive

    .gender= @client.gender
    .age= @client.age
    .race= @client.race
%h3 Reports
= render "reports/report_table", reports: @client.reports, responders: @available_responders
.row
  %br
  - status = @client.active ? 'Deactivate' : 'Reactivate'
  .col-sm-2= link_to "#{status}", client_path(@client, client: {active: !@client.active}), method: :put, class: 'btn btn-warning'
  .col-sm-2= link_to 'Edit', edit_client_path(@client), class: 'btn btn-default'