config/routes.rb
Streetmom::Application.routes.draw do

  devise_for :users, path_prefix: 'my'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  resources :reports, except: %w(edit) do
    collection do
      get 'active'
      get 'history'
    end

    member do
      post 'upload' => 'reports#update'
      get 'download' => 'reports#download', :as => :download
    end
  end

  resources :users, except: %w(destroy) do
    collection do
      get 'by_phone'
      get 'deactivated'
    end
    member do
      post 'start', to: 'shifts#start', :as => :start_shift
      post  'end',  to: 'shifts#end',   :as => :end_shift
    end
  end

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

  resources :clients, except: %w(destroy) do
    collection do
      get 'deactivated'
    end
  end

  resources :dispatches, only: %w(create update)
  resources :logs,       only: %w(create update)
  resources :reporters,  only: %w(show create new)
  resources :sms,        only: %w(create)

  resources :reporter_locations, only: %w(create)

  resources :uploads,    only: %w(destroy)

  resources :timeline_map do
    collection do
      get 'timeline_map' => 'timeline_map#index'
    end
  end

  get '/visualizations/reports_timeline_map', to: 'visualizations#reports_timeline_map'

  get '/visualizations/reports_charts', to: 'visualizations#reports_charts'
end

app/models/report.rb
class Report < ActiveRecord::Base
  include CsvExportable
  sensitive_fields :name, :phone, :nature

  include PgSearch

  DEFAULT_TEAM_NAME = "Concrn Team"
  attr_accessor :delete_image
  serialize :observations, Array
  reverse_geocoded_by :lat, :long do |obj, results|
    obj.zip ||= results.first.postal_code if results.first
  end
  after_validation :reverse_geocode

  # RELATIONS #
  has_many :dispatches, dependent: :destroy
  has_many :logs,       dependent: :destroy
  has_many :responders, through:   :dispatches
  has_many :uploads, dependent: :destroy
  belongs_to :client

  accepts_nested_attributes_for :uploads, reject_if: :all_blank, allow_destroy: true

  # CALLBACKS #
  has_attached_file :image
  before_validation :clean_image, :clean_observations
  after_validation :set_completed, if: :archived_or_completed?, on: :update
  after_commit :push_reports
  after_create :send_to_dispatcher

  URGENCY_LABELS = ['Not urgent', 'This week', 'Today', 'Within an hour', 'Need help now']
  SETTING = ['Public Space', 'Workplace', 'School', 'Home', 'Other']
  OBSERVATION = ['At-risk of harm', 'Under the influence', 'Anxious', 'Depressed', 'Aggravated', 'Threatening' ]
  STATUS = %w(archived completed pending)

  # VALIDATIONS #
  validates :address, presence: true
  validates_inclusion_of :status, in: STATUS
  validates_inclusion_of :gender, in: Client::GENDER, allow_blank: true
  validates_inclusion_of :age, in: Client::AGEGROUP, allow_blank: true
  validates_inclusion_of :race, in: Client::ETHNICITY, allow_blank: true
  validates_inclusion_of :setting, in: SETTING, allow_blank: true
  validates_attachment :image, :content_type => { :content_type => %w(image/jpeg image/jpg image/png) }

  # SCOPE #
  scope :accepted, lambda {
    joins(:dispatches).where(dispatches: {status: 'accepted'}).distinct
  }

  scope :completed, -> { where(status: %w(completed archived)) }

  scope :pending, lambda {
    joins(:dispatches).where(dispatches: {status: 'pending'}).distinct
  }

  scope :unassigned, lambda {
    includes(:dispatches).where(status: 'pending')
      .where.not(id: pending.pluck(:id).concat(accepted.pluck(:id)))
  }

  scope :by_oldest, -> { order("reports.created_at ASC") }
  scope :by_newest, -> { order("reports.created_at DESC") }

  pg_search_scope :keyword_search, :against => [:name, :phone, :address, :status, :nature], :associated_against => {
      :responders => [:name],
      :logs => [:body],
      :client => [:name]
    }, 
    :using =>
      { tsearch: {prefix: true, dictionary: "english"}},
    :order_within_rank => "reports.created_at DESC"

  # INSTANCE METHODS #
  def accepted_dispatches
    dispatches.accepted
  end

  def multi_accepted_responders?
    accepted_dispatches.count > 1
  end

  def primary_responder
    return false if accepted_dispatches.blank?
    accepted_dispatches.oldest.responder
  end

  def current_status
    return 'completed' if completed?
    return 'active' if active?
    return 'pending' if pending?
    return 'archived' if archived?
    return 'unassigned'
  end

  def dispatch(responder)
    dispatches.create(responder: responder)
  end

  def accepted?
    Responder.accepted(id).any?
  end

  def archived?
    status == 'archived'
  end
  
  def pending?
    dispatches
      .where.not(status: 'accepted')
      .where.not(status: 'completed')
      .where.not(status: 'rejected').any?
  end

  def active?
    dispatches.where(status: 'accepted').any?
  end
  
  def completed?
    dispatches.where(status: 'completed').any?
  end

  def archived_or_completed?
    archived? || completed?
  end

  def complete
    update_attributes(status: 'completed')
  end

  def set_completed
    return false unless %w(archived completed).include?(status)
    touch(:completed_at) unless completed_at.present?
    dispatches.pending.each { |i| i.update_attributes(status: 'rejected') }
    Dispatch.accepted(id).each { |i| i.update_attributes(status: 'completed') }
  end

  def neighborhood
    read_attribute(:neighborhood) || update_attribute(:neighborhood, Neighborhood.at(lat, long)) && read_attribute(:neighborhood)
  end

  def get_similar_reports(number_of_reports = 5)
    similar_reports = Report
      .where("gender = ? OR gender = ?", self.gender, 'Other')
      .where(age: self.age)
      .where.not(id: self.id)
      .to_a

    similar_reports.sort_by! do |report|
      0 - get_similarity_score(report)
    end

    similar_reports.first(number_of_reports)
  end

  private

  def send_to_dispatcher
    Dispatcher.on_shift.each do |dispatcher|
      Telephony.send("New Report @ #{address}. www.concrn.com/reports", dispatcher.phone)
    end
  end

  def clean_image
    image.clear if delete_image == '1'
  end

  def clean_observations
    observations.delete_if(&:blank?) if observations_changed?
  end

  def push_reports
    Push.refresh
  end

  def score_for_matched_observations(observations)
    observations.reduce(0) do |sum, observation|
      sum += 0.1 if self.observations.include?(observation)
    end
  end

  def get_similarity_score(other_report)
    score = 0
    self_report_time = self.created_at.hour * 60 + self.created_at.min
    other_report_time = other_report.created_at.hour * 60 + other_report.created_at.min

    score += 0.33 if other_report.race == self.race

    # unweighting these, but could be possible alterations to the algorithm
    #score += score_for_matched_observations(other_report.observations)
    #score += 0.33 if (other_report_time - self_report_time).abs <= 2 * 60

    score
  end
end

app/controllers/reports_controller.rb
class ReportsController < DashboardController
  before_action :authenticate_user!,       except: %w(new create update)
  before_action :authenticate_dispatcher!, only: %w(index active history)

  before_action :available_responders, only: %w(index active show history)
  before_action :find_report,          only: %w(destroy update show download)

  def new
    @report = Report.new
  end

  def index
    @unassigned_reports = Report.unassigned.by_newest.page(params[:unassigned_page]).per(10)
    @pending_reports = Report.pending.by_newest.page(params[:pending_page]).per(10)
  end

  def active
    @reports = Report.accepted
  end

  def history
    reports = ReportFilter.new(params).query
    @reports = params[:show_all] ? reports : reports.page(params[:page])
    @search_item = params[:search_by_keyword]
    @report_count = @reports.length
  end

  def create
    @report = Report.new(report_params)
    respond_to do |format|
      if @report.save
        flash[:notice] = "Report successfully created"
        format.js { render json: Presenter::Report.present(@report) }
        format.html { redirect_to action: :index }
      else
        format.js { render json: @report }
        format.html { render :new }
      end
    end
  end

  def destroy
    @report.destroy!
    redirect_to action: :index
  end

  def update
    @report = Report.find(params[:id])
    @report.dispatches.sample.complete! if params.fetch(:report)['status'] == 'completed'
      
    @report.update_attributes!(report_params)
    respond_to do |format|
      format.js { render json: {success: true} }
      format.html { redirect_to :back }
    end
  end

  def show
    @clients = Client.active
    render
  end

  def download
    file = open(@report.image.url)
    send_data file.read, filename:    @report.image_file_name,
                         type:        @report.image_content_type,
                         disposition: 'attachment',
                         stream:      'true',
                         buffer_size: '4096'
  end

  private

  def available_responders
    @available_responders = Responder.available
  end

  def find_report
    @report = Report.find(params[:id])
  end

  def report_params
    report_attributes = [
      :client_id, :name, :phone, :lat, :long, :status, :nature, :delete_image,
      :setting, { observations: [] }, :age, :gender, :race, :address,
      :neighborhood, :image, :urgency, :zip, uploads_attributes: [:file,
                                                                  :_destroy]
    ]

    params.require(:report).permit report_attributes
  end
end

app/views/reports/_assign_client.html.haml
= simple_form_for(report, html: {class: 'assign-client'}) do |f|
  = f.input :client_id, collection: clients, label: false, include_blank: 'None'

app/views/reports/_logroll.haml
.logroll
  %li.list-group-item
    %h4.list-group-item-heading
      .row
        .transcript-head.col-sm-6
          = "Transcript#{' with ' if report.accepted? }"
        .col-sm-6
          %span{style: 'float:right;'}
            - Responder.accepted(report.id).each do |responder|
              .responder{style: 'float:right;'}
                = link_to responder.name, user_path(responder)
                = "@ #{responder.phone}"
              %br
    %table.table#transcript
      %tbody
        - previous_log = LogPresenter.new(report)
        - report.logs.each do |log|
          - log_presenter = LogPresenter.new(log)
          - unless log_presenter.date_created == previous_log.date_created
            = log_presenter.date_created
          - previous_log = log_presenter
          = content_tag_for :tr, log, class: 'log-entry' do
            = log_presenter.created_at
            = log_presenter.name
            = log_presenter.body
            = log_presenter.sms

  %li.list-group-item.metaphone
    = simple_form_for Log.new, remote: true do |f|
      .row
        .col-md-12= f.input :body, as: :string, label: false, placeholder: 'Enter details...'
        = f.input :author_id, as: :hidden, input_html: { value: current_user.id }
        = f.input :report_id, as: :hidden, input_html: { value: report.id }

app/views/reports/_report.html.haml
- report_presenter = ReportPresenter.new(report)
= content_tag_for :tr, report, class: "freshness-#{report_presenter.freshness}" do
  %td{title: report.created_at.to_s}
    %strong
      .digits= "#{report.created_at.in_time_zone(Streetmom::TIME_ZONE).strftime("%I:%M %p")}"
      .time-ago.words
        (
        %abbr.timeago{title: report.created_at.getutc.iso8601}= report.created_at.to_s
        )
      .show_link= link_to("Show Details", report)

  %td= link_to report.name, reporter_path(report, reporter: {name: report.name})

  %td= link_to report.phone, reporter_path(report, reporter: {phone: report.phone})

  %td
    - if report.gender?
      %dt Gender
      %dd= report.gender
    - if report.age?
      %dt Age
      %dd= report.age
    - if report.race?
      %dt Race
      %dd= report.race

  %td
    - if report.nature?
      %dd=report.nature
    - if report.setting?
      %dt Setting
      %dd= report.setting
    - if report.observations?
      %dt Observations
      %dd= report.observations * ', '
    - if report.urgency?
      %dt Urgency
      %dd= urgency_label(report.urgency)

  %td
    %dd= link_to report.address, google_maps(report.address), target: '_blank'
    %br
    - if report.image.present?
      %a{:target => "_blank", :href => report.image.url(:original)}
        %img{:src => report.image.url, :style => 'width:100px;height:auto;'}

  %td{class: "report-#{report.id}-dispatch"}
    = render "dispatches/create", report: report, responders: responders unless report.archived_or_completed?
    - if report.dispatches.present?
      = render "dispatches/index", report: report
    - elsif report.archived? && report.dispatches.empty?
      No one assigned

  %td
    - if report.client
      =link_to report.client.name, client_path(report.client)
    - elsif
      None

app/views/reports/_report_table.html.haml
%table.table.pusher
  %thead
    %tr
      %th
        Date
        = link_to "<span class='glyphicon glyphicon-chevron-#{params[:order] == 'asc' ? 'up' : 'down'}'></span>".html_safe,
          history_reports_path(start_date: params[:start_date],
          end_date: params[:end_date],
          order: (['desc', 'asc'] - [params[:order]])[0]) if current_page?('/reports/history')
      %th Name
      %th Phone
      %th Client Description
      %th Incident
      %th Location
      %th Responders
      %th Client
  - if reports.none?
    %tbody
      %tr
        %td{colspan: 7} No Reports
  - else
    %tbody= render reports, responders: responders

app/views/reports/_upload_fields.html.haml
%fieldset
  = f.input_field :file
  = f.hidden_field :_destroy
  = link_to "remove", '#', class: "remove_fields"

app/views/reports/active.html.haml
%h2 Active
= render "report_table", reports: @reports, responders: @available_responders

app/views/reports/create.html.haml
%h2 Unassigned
= render "report_table", reports: @unassigned_reports, responders: @available_responders
%h2 Pending
= render "report_table", reports: @pending_reports, responders: @available_responders

app/views/reports/filter.js.erb
<% if defined?(@report) %>
  $('.pagination').hide();
  $("tr#report_<%= @report.id %>").closest('table').html("<%= escape_javascript(render :partial => 'reports/report_table', :locals => { :reports => @reports, responders: @available_responders } ) %>");
<% elsif @reports.present? %>
  $('.pagination').hide();
  $("table").html("<%= escape_javascript(render :partial => 'reports/report_table', :locals => { :reports => @reports, responders: @available_responders } ) %>");
<% else %>
  $('tbody').html('No Reports');
<% end %>

app/views/reports/history.html.haml
%h2 History
.row
  = simple_form_for '', url: history_reports_path, method: :get do |f|
    .col-sm-2= f.input :start_date, label: 'Start',
      input_html: {class: 'date col-sm-2', value: params[:start_date]}
    .col-sm-2= f.input :end_date, label: 'End',
      input_html: {class: 'date col-sm-2', value: params[:end_date]}

    .col-sm-1= f.button :submit, 'Search Dates', style: 'margin-top:25px;'
    .col-sm-1= link_to 'Show All', history_reports_path(start_date: params[:start_date],
      end_date: params[:end_date], order: params[:order], show_all: true), class: 'btn btn-primary',
      style: 'margin:25px; margin-right:43px;'

  = simple_form_for '', defaults: { input_html: { class: 'keyword_search' } }, url: history_reports_path, method: :get do |f|
    .col-sm-1
    .col-sm-3= f.input :search_by_keyword, label: 'Search Keywords',
      input_html: {class: 'col-sm-2', value: params[:search_by_keyword]}
    .col-sm-1= f.button :submit, 'Search', style: 'margin-top:25px;'

- if @report_count == 1
  %p= "Found #{@report_count} report matching #{@search_item}"
- elsif !@search_item
  %p= "Found #{@report_count} reports"
- else
  %p= "Found #{@report_count} reports matching \'#{@search_item}\'"


= render "report_table", reports: @reports, responders: @available_responders

= paginate @reports unless params[:show_all]

= content_for :footer_js do
  :javascript
    var ready;
    ready = function() {
      $('.date').datepicker({
        dateFormat: 'M d, yy'
      })
    };

    $(document).ready(ready);
    $(document).on('page:load', ready);

app/views/reports/index.html.haml
%h2 Unassigned
= render "report_table", reports: @unassigned_reports, responders: @available_responders
= paginate @unassigned_reports, param_name: :unassigned_page

%h2 Pending
= render "report_table", reports: @pending_reports, responders: @available_responders
= paginate @pending_reports, param_name: :pending_page

app/views/reports/new.html.haml
%h2 Create a report
.report-form
  = simple_form_for @report do |f|
    %h4 Location
    .col-md-9= f.input :address
    .col-md-3= f.input :zip, label: "Zip Code"
    %h4 Reporting Party Information
    .col-md-6= f.input :name, label: "Contact Name",
      input_html: { value: current_user.try(:name) }
    .col-md-6= f.input :phone, label: "Contact Phone No.", placeholder: "4158675309",
      type: "tel", maxlength: "10", required: true, hint: "10-digit US numbers only",
      input_html: { value: current_user.try(:phone) }

    .col-md-12
      = f.input :urgency,  collection: Report::URGENCY_LABELS.map.with_index {|label, i| [label, i+1]}
      %div.form-group
        %label.control-label Is this report concerning a person?
        %input#is-person.form-control{type: 'checkbox'}
      %div#person-fields{style: 'display:none;'}
        %h4 Patient Description
        = f.input :gender, collection: Client::GENDER
        = f.input :age, collection: Client::AGEGROUP
        = f.input :race, collection: Client::ETHNICITY
        = f.input :setting, collection: Report::SETTING
        %h4 Incident Description
        .observation-checkboxes
          = f.input :observations, as: :check_boxes, collection: Report::OBSERVATION
      = f.input :nature, label: "Additional Description"
      = f.input_field :image

      = f.simple_fields_for :uploads do |builder|
        = render 'upload_fields', f: builder
      = link_to_add_fields "Add Another File", f, :uploads
      %br
    .new-submit= f.submit 'Submit Report', class: 'btn btn-primary'


= content_for :footer_js do
  :javascript
    $(document).on('change', '#is-person', function(){
      var status = this.checked ? 'show' : 'hide';
      $('#person-fields')[status]();
    });

app/views/reports/show.html.haml
%h2.pusher-id{'data-id' => @report.id, 'data-type' => 'report'}
  = @report.neighborhood ? "Report in #{@report.neighborhood}" : "Reported"
  %small
    %abbr.timeago{title: @report.created_at.getutc.iso8601}= @report.created_at.to_s
.row
  %ul.list-group.col-md-4
    %li.list-group-item
      .btn-archive.list-group-item-text.pull-right= link_to 'Archive', report_path(@report, report: {status: 'archived'}), 'data-confirm' => 'Are you sure you want to archive the report?', method: :put, class: 'btn btn-warning' unless @report.archived_or_completed?
      .btn-complete.list-group-item-text.pull-right= link_to 'Complete', report_path(@report, report: {status: 'completed'}), 'data-confirm' => 'Are you sure you want to complete the report?', method: :put, class: 'btn btn-success' unless @report.archived_or_completed?

      %h4.list-group-item-heading Status
      .list-group-item-text= @report.current_status.capitalize

    %li.list-group-item
      %h4.list-group-item-heading Reported at
      .list-group-item-text=@report.created_at

    %li.list-group-item
      %h4.list-group-item-heading Reporting Party
      .list-group-item-text=@report.name
      .list-group-item-text=@report.phone

    %li.list-group-item
      %h4.list-group-item-heading Address
      .list-group-item-text=@report.address

    - if @report.urgency?
      %li.list-group-item
        %h4.list-group-item-heading Urgency
        .list-group-item-text= urgency_label(@report.urgency)

    - if @report.nature? || @report.age? || @report.race? || @report.gender?
      %li.list-group-item
        %h4.list-group-item-heading Client Description
        .list-group-item-text="#{@report.age} #{@report.race} #{@report.gender}"
        .list-group-item-text=@report.nature

    %li.list-group-item
      %h4.list-group-item-heading Client
      = render partial: "reports/assign_client", locals: { report: @report, clients: @clients }
      - if @report.client
        %dl
          %dt
            Age
          %dd= @report.client.age
          %dt
            Ethnicity
          %dd= @report.client.race
          %dt
            Gender
          %dd= @report.client.gender

    - if @report.observations?
      %li.list-group-item
        %h4.list-group-item-heading Observations
        .list-group-item-text=@report.observations.join(', ')

    %li.list-group-item
      %h4.list-group-item-heading Files
      - if @report.image.present?
        .list-group-item-text= link_to "Download #{@report.image_file_name}", download_report_path(@report)
        %a{:target => "_blank", :href => @report.image.url(:original)}
          %img{:src => @report.image.url, :style => 'width:200px;height:auto;'}
        .list-group-item-text= link_to "Remove File", report_path(@report, "report[delete_image]" => '1'), method: :put
      - else
        .list-group-item-text
          = simple_form_for @report do |f|
            = f.input_field :image
            %br
            = f.button :submit, 'Add File'
      - @report.uploads.each do |upload|
        .report-file
          .list-group-item-text= upload.file_file_name
          %a{:target => "_blank", :href => upload.file.url }
            %img{:src => upload.file_image_url, :style => 'width:200px;height:auto;'}
          .list-group-item-text= link_to "Remove File", upload_path(upload), method: :delete

    .btn-delete
      = link_to 'Delete', report_path(@report), method: :delete,
      'data-confirm' => 'Are you sure you want to delete the report? All dispatches and records of this report will be destroyed permanently.', class: 'btn btn-danger'

  %ul.list.group.col-md-8
    = render partial: "reports/logroll", locals: {report: @report}
    .col-md-6
      %br
      %br
      %td{class: "@report-#{@report.id}-dispatch"}
      = render partial: "dispatches/create", locals: { report: @report, responders: @available_responders } unless @report.archived_or_completed?
    .col-md-6
      %br
      - if @report.dispatches.present?
        = render partial: "dispatches/index", locals: { report: @report }

  / While "similar reports" could become a useful feature, it is disabled because it currently serves as a non-functional distraction to dispatchers.
  / .col-md-8
  /   %h3 Reports that might be for the same client
  /   = render "report_table", reports: @report.get_similar_reports, responders: []