config/routes.rb
Streetmom::Application.routes.draw do

  devise_for :users, path_prefix: 'my'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  resources :reports, except: %w(edit) do
    collection do
      get 'active'
      get 'history'
    end

    member do
      post 'upload' => 'reports#update'
      get 'download' => 'reports#download', :as => :download
    end
  end

  resources :users, except: %w(destroy) do
    collection do
      get 'by_phone'
      get 'deactivated'
    end
    member do
      post 'start', to: 'shifts#start', :as => :start_shift
      post  'end',  to: 'shifts#end',   :as => :end_shift
    end
  end

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

  resources :clients, except: %w(destroy) do
    collection do
      get 'deactivated'
    end
  end

  resources :dispatches, only: %w(create update)
  resources :logs,       only: %w(create update)
  resources :reporters,  only: %w(show create new)
  resources :sms,        only: %w(create)

  resources :reporter_locations, only: %w(create)

  resources :uploads,    only: %w(destroy)

  resources :timeline_map do
    collection do
      get 'timeline_map' => 'timeline_map#index'
    end
  end

  get '/visualizations/reports_timeline_map', to: 'visualizations#reports_timeline_map'

  get '/visualizations/reports_charts', to: 'visualizations#reports_charts'
end

app/views/layouts/_footer.html.haml
%footer
  %br
  %p © 2014 Concrn Inc.

app/views/layouts/_header.html.haml
%header
    %br
    %br
    %br

app/views/layouts/_navbar.html.haml
.container
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
      %img{src: asset_path("mobile-menu.png")}/
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: "/"}
  .navbar-collapse.collapse.drop-nav
    - if user_signed_in?
      %ul.nav.navbar-nav
        - if current_user.role == 'dispatcher'
          %li= link_to 'Dispatch', reports_path
          %li= link_to "Active", active_reports_path
          %li= link_to "History", history_reports_path
          %li= link_to "Users", users_path if current_user.dispatcher?
          %li= link_to "Clients", clients_path
        %li= link_to "Create Report", new_report_path
      .navbar-right.navbar-text
        Logged in as
        %strong
          = "#{current_user.name}"
        = link_to 'Profile', edit_user_path(current_user), class: 'navbar-link'
        |
        = link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'
    - else
      #sign-in-form
        = simple_form_for(:user, url: session_path(:user), html: {class: "navbar-form navbar-right"}) do |f|
          = f.input :email, placeholder: "email",  label: false
          = f.input :password, type: :password, placeholder: "password", label: false
          = f.submit "Login", class: "btn btn-success"

          = link_to "Sign Up", new_reporter_path, class: 'btn btn-sign-up'

app/views/layouts/_notifications.html.haml
- if notice
  %p.alert.alert-success= notice
- if alert
  %p.alert.alert-warning= alert

app/views/layouts/application.haml
!!!
%html
  %head
    %title Concrn
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "//js.pusher.com/2.1/pusher.min.js"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %link{href: asset_path("concrn-favicon.png"), rel: "shortcut icon"}

  %body{"ng-app" => "concrnApp"}
    = conditional_nav_tag do
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %img{src: asset_path("mobile-menu-05.png")}/
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"}

        .navbar-collapse.collapse.drop-nav
          - if user_signed_in? && current_user.role == 'dispatcher'

            %ul.nav.navbar-nav
              %li= link_to 'Dispatch', reports_path
              %li= link_to "Active", active_reports_path
              %li= link_to "History", history_reports_path
              %li= link_to "Responders", responders_path
              %li= link_to "Create Report", new_report_path

            .navbar-right.navbar-text
              Logged in as
              %strong= current_user.email
              = link_to 'Profile', edit_user_registration_path, class: 'navbar-link'
              |
              = link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'

          - else
            #sign-in-form
              = simple_form_for(:user, url: session_path(:user), html: {class: "navbar-form navbar-right"}) do |f|
                = f.input :email, placeholder: "email",  label: false
                = f.input :password, type: :password, placeholder: "password", label: false
                = f.submit "Login", class: "btn btn-success"

    = yield :before_grid
    .container.main
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-warning= alert
      = yield
      %footer
        %br
        %br
        %p © Concrn (2014)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Concrn
    = csrf_meta_tags
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "//js.pusher.com/2.2/pusher.min.js"
    = javascript_include_tag "application"
    
    %meta{:content => "initial-scale=1,maximum-scale=1,user-scalable=no", :name => "viewport"}
    %script{:src => "https://api.tiles.mapbox.com/mapbox-gl-js/v0.16.0/mapbox-gl.js"}
    %link{:href => "https://api.tiles.mapbox.com/mapbox-gl-js/v0.16.0/mapbox-gl.css", :rel => "stylesheet"}
    %script{:src => "http://code.highcharts.com/highcharts.js"}
    
    %link{rel: "apple-touch-icon", sizes: "57x57", href: asset_path("apple-touch-icon-57x57.png")}
    %link{rel: "apple-touch-icon", sizes: "114x114", href: asset_path("apple-touch-icon-114x114.png")}
    %link{rel: "apple-touch-icon", sizes: "72x72", href: asset_path("apple-touch-icon-72x72.png")}
    %link{rel: "apple-touch-icon", sizes: "144x144", href: asset_path("apple-touch-icon-144x144.png")}
    %link{rel: "apple-touch-icon", sizes: "60x60", href: asset_path("apple-touch-icon-60x60.png")}
    %link{rel: "apple-touch-icon", sizes: "120x120", href: asset_path("apple-touch-icon-120x120.png")}
    %link{rel: "apple-touch-icon", sizes: "76x76", href: asset_path("apple-touch-icon-76x76.png")}
    %link{rel: "apple-touch-icon", sizes: "152x152", href: asset_path("apple-touch-icon-152x152.png")}
    %link{rel: "apple-touch-icon", sizes: "180x180", href: asset_path("apple-touch-icon-180x180.png")}
    %link{rel: "icon", type: "image/png", href: asset_path("favicon-192x192.png"), sizes: "192x192"}
    %link{rel: "icon", type: "image/png", href: asset_path("favicon-160x160.png"), sizes: "160x160"}
    %link{rel: "icon", type: "image/png", href: asset_path("favicon-96x96.png"), sizes: "96x96"}
    %link{rel: "icon", type: "image/png", href: asset_path("favicon-16x16.png"), sizes: "16x16"}
    %link{rel: "icon", type: "image/png", href: asset_path("favicon-32x32.png"), sizes: "32x32"}
    %meta{name: "msapplication-TileColor", content: "#f9f4ef"}
    %meta{name: "msapplication-TileImage", content: "/mstile-144x144.png"}
    %link{href:'http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900', rel: 'stylesheet'}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %meta{:charset => "utf-8"}
    %meta{:content => "initial-scale=1,maximum-scale=1,user-scalable=no", :name => "viewport"}
    %script{:src => "https://api.tiles.mapbox.com/mapbox-gl-js/v0.16.0/mapbox-gl.js"}
    %link{:href => "https://api.tiles.mapbox.com/mapbox-gl-js/v0.16.0/mapbox-gl.css", :rel => "stylesheet"}
    %script{:charset => "utf-8", :src => "//d3js.org/d3.v3.min.js"}

  %body{'data-pusher-key' => ENV['PUSHER_KEY']}
    = conditional_nav_tag do
      = render 'layouts/navbar'
    = yield :before_grid
    .container.main
      = render 'layouts/header'
      = render 'layouts/notifications'
      = yield
      = render 'layouts/footer'
  = yield :footer_js